// next imports
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// third parties imports
import { ConfigProvider, ConfigProviderProps } from 'antd';
import type { AppProps } from 'next/app'

// components imports
import CustomHeader from "@/components/Header/CustomHeader";
import CustomFooter from "@/components/CustomFooter";
// import theme from "@/components/theme";

//theme
const theme ={
  colorPrimary: '#d10064',
  colorLink: '#d10064',
  colorBorder: '#e5e7eb',
  borderRadius: 8,
  colorBgBase: 'rgb(255,255,255, 0.6)'
} as ConfigProviderProps['theme']

// const fontInter = Inter({
//   subsets: ["latin"],
//   display:'optional',
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};







export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={{...theme}}>
    <html lang="en">

      <body
        className={"w-full max-w-[1400px] mx-auto h-screen flex flex-col "  }
      >
        {<CustomHeader />}
        {children}
        {<CustomFooter />}
      </body>
    </html>
    </ConfigProvider>
  );
}
 